name: voltsense2
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

#---------------PACKAGES---------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages 
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  lottie: ^2.7.0
  connectivity_plus: ^5.0.1
  url_launcher: ^6.1.12
  #flutter_native_splash: ^2.4.5

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
   
  # State Management 
  get: ^4.7.2
  google_fonts: ^6.2.1
  fl_chart: ^0.70.2
  #Product Specific

  # Firebase
  firebase_core: ^3.12.1
  get_storage: ^2.1.1
  firebase_auth: ^5.5.1
  flutter_native_splash: ^2.4.4
  cloud_firestore: ^5.6.5
  flutter_libphonenumber: ^2.5.1
  

  # -------------------- ./PACKAGES END --------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  #-------------------LOCAL ASSETS----------------#
  assets:
    - assets/fonts/
    - assets/images/

  #-----------------LOCAL FONTS----------------#
#  fonts:
#    - family: Schyler
#      fonts:
#        - asset: assets/fonts/Schyler-Regular.ttf
#        - asset: assets/fonts/Schyler-Italic.ttf
#          style: italic
#    - family: Trajan Pro
#      fonts:
#        - asset: assets/fonts/TrajanPro.ttf
#        - asset: assets/fonts/TrajanPro_Bold.ttf
#          weight: 700