// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEKdG3s90CEmlWjoqZRYbXtgw9vGyb1-0',
    appId: '1:110999938896:web:36a1e646efe052458e2e55',
    messagingSenderId: '110999938896',
    projectId: 'voltsense-9ff7b',
    authDomain: 'voltsense-9ff7b.firebaseapp.com',
    storageBucket: 'voltsense-9ff7b.firebasestorage.app',
    measurementId: 'G-5D9HZ89YQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX44bi0EduW0eGrIdnSGYjkToAVn1Z120',
    appId: '1:110999938896:android:977eef3f32119afd8e2e55',
    messagingSenderId: '110999938896',
    projectId: 'voltsense-9ff7b',
    storageBucket: 'voltsense-9ff7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfxeXtwC8kWQ8Z5ntwzk1Hi6zCGO29Cis',
    appId: '1:110999938896:ios:d482ee3a18336ccd8e2e55',
    messagingSenderId: '110999938896',
    projectId: 'voltsense-9ff7b',
    storageBucket: 'voltsense-9ff7b.firebasestorage.app',
    androidClientId: '110999938896-jkbb6em44fpsmisikrn5apu4vttmqp8h.apps.googleusercontent.com',
    iosClientId: '110999938896-85b779fmvjmolihcj9ahjk4l9h32g5ji.apps.googleusercontent.com',
    iosBundleId: 'com.example.voltsense2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfxeXtwC8kWQ8Z5ntwzk1Hi6zCGO29Cis',
    appId: '1:110999938896:ios:d482ee3a18336ccd8e2e55',
    messagingSenderId: '110999938896',
    projectId: 'voltsense-9ff7b',
    storageBucket: 'voltsense-9ff7b.firebasestorage.app',
    androidClientId: '110999938896-jkbb6em44fpsmisikrn5apu4vttmqp8h.apps.googleusercontent.com',
    iosClientId: '110999938896-85b779fmvjmolihcj9ahjk4l9h32g5ji.apps.googleusercontent.com',
    iosBundleId: 'com.example.voltsense2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEKdG3s90CEmlWjoqZRYbXtgw9vGyb1-0',
    appId: '1:110999938896:web:8025fa3e620e03c98e2e55',
    messagingSenderId: '110999938896',
    projectId: 'voltsense-9ff7b',
    authDomain: 'voltsense-9ff7b.firebaseapp.com',
    storageBucket: 'voltsense-9ff7b.firebasestorage.app',
    measurementId: 'G-Q4FQ50D71H',
  );

}